# Sort and Concate

In [2]:
import numpy as np
x = np.array([9,0.2,-1,5,4,12])


* Sort()

In [ ]:
np.sort(x) #ascending

array([-1. ,  0.2,  4. ,  5. ,  9. , 12. ])

In [ ]:
# Desending order if you flip ascending order it becomes desending
np.flip(np.sort(x)) 

array([12. ,  9. ,  5. ,  4. ,  0.2, -1. ])

* Concatenate()

In [1]:
# In list concate
a = [2,4]
b = [3,8,1]

In [2]:
a + b

[2, 4, 3, 8, 1]

In [5]:
# In array concate
a =np.array([2,4])
b = np.array([3,8,1])

In [6]:
# In Array does not concate together with different shape data using (+) operator.
a+b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [8]:
# In Array we use concate two value using concatenate() method
np.concatenate((a,b))

array([2, 4, 3, 8, 1])

# Vector operations and brodcasting


In [9]:
x = np.array([8,4,2])
y = np.array([2,4,2])


* Vector Basic Arithmetic operation: 

Vetor operation perform when we have an equal shape of the array.

In [10]:
# Addition
x + y

array([10,  8,  4])

In [ ]:
# Subtraction
x-y

array([6, 0, 0])

In [ ]:
# Multiplications
x * y

array([16, 16,  4])

In [ ]:
# Exponant
x ** y

array([ 64, 256,   4])

* Brodcasting

Brodcasting allow operations between different shape of the array.

In [ ]:
a = np.array([8,9,6,1])

In [ ]:
2 * a # brodcasting

array([16, 18, 12,  2])

In [ ]:
3 + a

array([11, 12,  9,  4])

In [4]:
# Lets work brodcast with different shape of the array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,11,12]) # b brodcast automatically to expand the a
result = a + b
result

array([[11, 13, 15],
       [14, 16, 18]])

# Statistics using Numpy

In [11]:
# Generate random number
np.random.seed(0)
data = np.random.randint(1,50,5)
data

array([45, 48,  1,  4,  4])

In [ ]:
# mean
np.mean(data)

20.4

In [ ]:
# median
np.median(data)

4.0

In [ ]:
# To calculate the mode we need to import scipy library
from scipy.stats import mode
mode(data) # mode 4 is the frequency or count 2

ModeResult(mode=4, count=2)

In [ ]:
np.std(data) # standard deviation

21.35977527971678

In [ ]:
np.var(data) # variance

456.23999999999995

In [ ]:
np.min(data) # To calculate minimum value

1

In [ ]:
np.max(data) # To calculate maximum value

48

In [12]:
range = np.max(data) - np.min(data) # To calculate range value
range

47

In [13]:
# To find the index out  of the data where maximum value(48)
np.argmax(data)

1

In [14]:
# To find the index of the minimum value(1)
np.argmin(data)

2

# .any() vs .all()

In [16]:
height = np.array([1,2,3,4,5,6,6,5,4,3,2,1])

* .any()

It return True if one situation is match.

In [17]:
height >= 5 # is there any person with height >= 5?

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False, False])

In [18]:
np.any(height >= 5)

True

* .all()

It return True when all the situation is match.

In [20]:
np.all(height>=5) # is there all person with height >= 5?

False

In [21]:
# To find  the how many person and who  are present (height >=5) 
height[height >= 5]

array([5, 6, 6, 5])

In [ ]:
# To find out grater than 3 and  less than 5
height[height>3 and height < 5] # numpy array doesn't support logical operator

ValueError: ignored

In [22]:
# while we use bitwise operator
height[(height>3) & (height < 5)] # when we use all the bitwise operator we need to close condtion in brackets

array([4, 4])

# Two Dimensional array

In [25]:
data = [ [1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(data)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matrix.shape # (no.of rows, no.of colums)

(3, 3)

In [ ]:
matrix.ndim # check the dimension

2

In [27]:
# To find the value 6
matrix[1,2]

6

In [ ]:
# To find the value 9
matrix[2,2]

9

In [ ]:
#To find the value 4
matrix[1,0]

4

In [ ]:
# To find the value 8
matrix[2,1]

8

In [ ]:
matrix[1,:] # To find the[4,5,6]

array([4, 5, 6])

In [ ]:
matrix[2,:]# To find the[7,8,9]

array([7, 8, 9])

In [31]:
matrix[:,2]# To find the[3,6,9]

array([3, 6, 9])

In [32]:
matrix[:,0]# To find the[1,4,7]

array([1, 4, 7])

In [ ]:
matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[1:,1:] # To find the[[5,6],[8,9]]

array([[5, 6],
       [8, 9]])

In [30]:
matrix[:2,1:] # To find the[[2,3],[5,6]]

array([[2, 3],
       [5, 6]])

In [ ]:
matrix[1:,:2]# To find the[[4,5],[7,8]]

array([[4, 5],
       [7, 8]])

In [ ]:
matrix[:2,1:] # To find the[[2,3],[5,6]]

array([[2, 3],
       [5, 6]])