<a href="https://colab.research.google.com/github/ashmi721/Data_Science_Class/blob/main/NumpyDS600_D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
The fundamental package for scientific computing with Python

In [ ]:
! pip install numpy



# How to import Numpy
We shorten the imported name to np for better readability of code using NumPy. This is a widely adopted convention that makes your code more readable for everyone working on it. We recommend to always use import numpy as np.

In [2]:
import numpy as np


In [10]:
# Checking version of numpy
np.__version__

'1.24.3'

# Creating Array

In [1]:
even = [2,44,4,8,2,6,18]
type(even)

list

In [ ]:
even_array = np.array(even)
even_array

array([ 2, 44,  4,  8,  2,  6, 18])

In [ ]:
type(even_array) # ndarray means n-dimensional array

numpy.ndarray

In [ ]:
even_array.ndim # shows number of dimensional(n) it is 1 dimensional array

1

In [ ]:
len(even_array) # checking the length of the even_array

7

In [ ]:
# checking number of dimensinal shape
even_array.shape

(7,)

In [ ]:
odd = [3,5,9,21,35,67,81,45]
type(odd)

list

In [ ]:
# convert list into array
odd_array = np.array(odd)
odd_array

array([ 3,  5,  9, 21, 35, 67, 81, 45])

# Random Number generations using NUmpy


In [ ]:
np.random.randint(1,100) # generating one random number between 1 - 100

52

In [ ]:
np.random.seed(2023)
np.random.randint(1,100) # Deterministic pseudorandom number generations

88

# Indexing and Slicing

In [ ]:
np.random.seed(0)
x = np.random.randint(1,100,size =8)
x

array([45, 48, 65, 68, 68, 10, 84, 22])

In [ ]:
x[1]

48

In [ ]:
x[-2] # find negative index

84

In [ ]:
x[3:6] # find between 68 to 84 using slicing

array([68, 68, 10])

In [ ]:
# find last 3 item
x[-3:]

array([10, 84, 22])

In [ ]:
x[::2] # slicing index skip 2

array([45, 65, 68, 84])


# Different between List and Numpy array
* Numpy array are memory effecient than python list.
* Numpy array are faster than python list.
* Numpy arrary support homogenous data type while python list support multiple data type.

In [ ]:
l1 = [0,0.25,0.5,0.75,1] # By default list contain 64-bit memory space

# Numpy array are memory effecient than python list
Specifying data type While the default data type is floating point (np.float64),we can explicitly specify which data type we want using the dtype keyword.

In [ ]:
l1_array = np.array(l1)
l1_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
l1_array.dtype #  check the memory bit

dtype('float64')

In [ ]:
# we can use the Numpy array to specify the memory space that's why Numpy array has an more effiecient
np.array(l1,dtype=np.float16)

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float16)

In [ ]:
np.ones(shape=5,dtype=np.int8)

array([1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.zeros(shape=4,dtype=np.int8)

array([0, 0, 0, 0], dtype=int8)

#  Numpy array are faster than python list.

In [ ]:
np.random.seed(0)
x_array = np.random.randint(low=1,high=100,size=50000)
x_array

array([45, 48, 65, ..., 59, 44, 91])

In [ ]:
x_list = x_array.tolist() # converting array to list
type(x_list)

list

In [ ]:
# To find the how many time consume to run the shell
%%time
sq = [item **2 for item in x_list]

CPU times: user 16.5 ms, sys: 1.81 ms, total: 18.3 ms
Wall time: 19.9 ms


In [ ]:
%%time
sq =  x_array ** 2

CPU times: user 177 µs, sys: 0 ns, total: 177 µs
Wall time: 186 µs


# List support multiple datatypes however, array supports homogeneous dataype

In [11]:
# list return  indivisual and own datatypes of the data
x =[True,0,55.3,'Hello']
type(x[0]),type(x[1]) 

(bool, int)

In [12]:
x_array = np.array(x)
x_array

array(['True', '0', '55.3', 'Hello'], dtype='<U32')

In [13]:
# Numpy array return the suitable datatypes of the data
type(x_array[0]),type(x_array[1]) 

(numpy.str_, numpy.str_)

# .arange()
We can generate the number using .arange() like a range()

In [ ]:
x = np.arange(1,10,2) # In Numpy use arange() like range() in list
x

array([1, 3, 5, 7, 9])

# .linspace()
we can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [ ]:
np.linspace(0,1,5) # generate  5 numbers between 0 t0 1 with equal width

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# .full()

* Initializing Numpy array with same number

In [7]:
np.full((2,2),7) # Syntax .full((matrix shape),repeted number)


array([[7, 7],
       [7, 7]])

In [8]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

# joining Numpy Arrays



In [10]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

* vstack()

Joining vertically

In [11]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

* hstack()

Joining horizontally

In [12]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

* column_stack()

Joining column wise

In [13]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy Intersection & Difference

In [18]:
n1=np.array([1,2,3,4])
n2=np.array([4,5,3,6,7])

In [15]:
# To find the common number
np.intersect1d(n1,n2)

array([3, 4])

In [19]:
# To find the unique element in n1
np.setdiff1d(n1,n2)

array([1, 2])

# Numpy save and load

In [20]:
# save the Numpy data
np.save('myarray',n1)

In [22]:
# load the numpy save file
np.load('myarray.npy')

array([1, 2, 3, 4])