In [3]:
import numpy as np

# Matrix multiplication or dot product
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGNq2BilK-CFEjRhELGBtSdZmG1HH57bu798_Bl3rqQg&s">

* vector matrix is the cross product(a*b) which isn't multiply by different rows and column like this image

* Scalar multiplication is a straightforward method of multiplying matrices, and we can accomplish this using the NumPy dot() function

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])


In [ ]:
A.shape # let m * n

(2, 3)

In [ ]:
B.shape # let p * q

(3, 2)

In [ ]:
# if n == p vayo vane matrix multiply hunxa
output = np.dot(A,B)
output

array([[ 58,  64],
       [139, 154]])

# Determinant Transpose and Inverse of Matrix

 Determinant and Transpose help us analyze and manipulate this data also help to solving problem and understanding the relationship within the data.

* Transpose

Meaning: In simpler terms, you switch the rows and columns.

Example: Consider this 2x3 
The transpose would be a 3x2 matrix:
<img src="https://cdn1.byjus.com/wp-content/uploads/2021/09/Important-Questions-for-Class-10-Maths-Chapter-8-Introduction-to-Trigonometry-1.png">
 
It's like flipping the matrix.

In [ ]:
# Transpose (In Transpose row in column and colume is the row)
output.T

array([[ 58, 139],
       [ 64, 154]])

* Determinations

The determinant helps us find the inverse of a matrix, tells us things about the matrix that are useful in systems of linear equations, calculus and more.

<img src ="https://media.geeksforgeeks.org/wp-content/uploads/20220822110402/3x3.png">

In [ ]:
# To calculate the Determinations
det = np.linalg.det(output)
det

36.000000000000256

In [ ]:
np.round(det)

36.0

* Inverse

if you have a transformation that scales and rotates an object, applying the inverse transformation would bring the object back to its original state. In data analysis, finding the inverse is crucial for solving systems of linear equations and recovering original information from transformed data.

<img src ="https://mrwilliamsmath.weebly.com/uploads/1/3/1/4/13149046/published/inverse-matrix.gif">

In [ ]:
# To calculate the inverse
inv = np.linalg.inv(output)
inv

array([[ 4.27777778, -1.77777778],
       [-3.86111111,  1.61111111]])

# The axis argument in numpy: 2D axis=0 is column-wise and axis=1 means row-wise.

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# We want total sum of each item in an array
x.sum()

21

In [ ]:
# vertically sum
x.sum(axis=0)

array([5, 7, 9])

In [ ]:
# horizontally sum
x.sum(axis=1)

array([ 6, 15])

In [ ]:
# To calculate the verticle mean
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
# To calculate the horizontally mean'
x.mean(axis=1)

array([2., 5.])

# .reshape()

The reshape() is used to convert one dimension or shape  to another dimension or shape like (1D to 2D)(2,3)or (3,2)etc

In [ ]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [ ]:
x.shape

(6,)

In [ ]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Row matrix and column matrix

<img src="https://d20khd7ddkh5ls.cloudfront.net/row_column_matrices.jpg">

In [2]:
x = np.array([8,2,0,3,5,9])
x

array([8, 2, 0, 3, 5, 9])

In [3]:
# row matrix ma no.of row=1, column = unknown ; this unknown is represent by -1
x.reshape(1,-1)

array([[8, 2, 0, 3, 5, 9]])

In [4]:
# column matrix ma no.of row = unknown; column = 1; where as unknown represent -1

x.reshape(-1,1)

array([[8],
       [2],
       [0],
       [3],
       [5],
       [9]])

# Converting 2D array to 1D

flatten is most used in data cleanning or deep learning. also it is used to convert the 2D or 3D array to convert in 1D.

In [4]:
matrix = np.array([[2,6],[8,9]])
matrix

array([[2, 6],
       [8, 9]])

In [5]:
# flatten()
flat_array = matrix.flatten()
flat_array

array([2, 6, 8, 9])

In [6]:
flat_array.ndim

1

In [7]:
# to convert to array into list
flat_array.tolist()

[2, 6, 8, 9]

# Morden day Images are in 3D

`(channel,row, column)`

In [ ]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.random.rand(3,4,5)

array([[[0.91239038, 0.07924515, 0.96835307, 0.25370646, 0.32083212],
        [0.33967278, 0.97680984, 0.81618472, 0.44447794, 0.57372895],
        [0.36518984, 0.85875859, 0.39227677, 0.96599977, 0.20937318],
        [0.8575841 , 0.38114698, 0.12848951, 0.841727  , 0.6543123 ]],

       [[0.65221098, 0.32855198, 0.83182798, 0.65658724, 0.67577995],
        [0.72535505, 0.58487372, 0.72495381, 0.66851379, 0.98245623],
        [0.24321409, 0.04819083, 0.09862191, 0.64673708, 0.40523096],
        [0.88225306, 0.8493405 , 0.6137525 , 0.31608239, 0.35445127]],

       [[0.31033947, 0.77178534, 0.61638424, 0.913562  , 0.84927542],
        [0.27838715, 0.77289867, 0.21515222, 0.62670416, 0.53261071],
        [0.17638663, 0.87428683, 0.73344425, 0.10572735, 0.95586559],
        [0.19629932, 0.88051505, 0.51455275, 0.69335174, 0.87764786]]])